version: '3'


services:
  zookeeper:
    image: zookeeper:3.6
    ports:
      - "2181:2181"
    env_file: ./.env/zookeeper.env
    restart: always
    volumes:
      - ./zdata:/data
      - ./zdatalog:/datalog
    healthcheck:
      test: ["CMD", "nc", "-w", "2", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      kafka-network:
        ipv4_address: 172.20.10.2
  
  

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    env_file: ./.env/kafka.env
    depends_on:
      - zookeeper
    networks:
      kafka-network:
        ipv4_address: 172.20.10.3



networks:
  kafka-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.10.0/24
