version: '3'

services:  
  kafka:
    container_name: kafkaBroker1
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    env_file: ./.env/kafka.env
    volumes:
      - "./kafka:/bitnami"
    networks:
      kafka-network:
        ipv4_address: 172.20.10.3
    healthcheck:
      test: ["CMD", "nc", "-w", "2", "localhost", "9092"]
      interval: 15s
      timeout: 5s
      retries: 3
 
networks:
  kafka-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.10.0/24